[versions]
agp = "8.1.0-beta01"
org-jetbrains-kotlin-android = "1.8.10"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.00"
compose-nav = "2.5.1"
compose-coil = "2.4.0"
compose-hilt = "1.0.0"
appcompat = "1.6.1"
material = "1.9.0"
di-hilt = "2.46.1"
di-inject = "1"
org-jetbrains-kotlin-jvm = "1.8.10"
orbit-core = "6.0.0"
kotlin-collections-immutable = "0.3.5"
plugin-kotlin-ksp = "1.8.10-1.0.9"
plugin-code-ktlint-core = "11.3.2"
retrofit = "2.9.0"
gson = "2.10.1"
okhttp = "4.11.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui-coil = { module = "io.coil-kt:coil-compose", version.ref = "compose-coil" }
compose-nav = { module = "androidx.navigation:navigation-compose", version.ref = "compose-nav"}
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlin-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-collections-immutable" }
compose-hilt = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "compose-hilt" }

di-hilt-core = { module = "com.google.dagger:hilt-android", version.ref = "di-hilt" }
di-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "di-hilt" }
di-inject = { module = "javax.inject:javax.inject", version.ref = "di-inject" }

orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbit-core" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbit-core" }
androidx-room-common = { group = "androidx.room", name = "room-common", version = "2.5.1" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version = "2.5.1" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version = "2.5.1" }

okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-core= { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", name = "gson", version.ref = "gson" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "di-hilt" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "plugin-kotlin-ksp" }
code-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "plugin-code-ktlint-core" }

